// Generated by 'unplugin-auto-import'
export {};
declare global {
  const MdiClose: typeof import("~icons/mdi/close.jsx")["default"];
  const MdiSearch: typeof import("~icons/mdi/search.jsx")["default"];
}
